global:
  imagePullPolicy: Always
  # vault:
  #  host: ip
  #  name: vault
  #  vaultToken: someToken
  # secret:
  #   DB_URI: mongodb://root:rootpassword@sausage-store-mongodb:27017/reports?authSource=admin
secrets:
  mongodb:
    rootUsername: root
    rootPassword: rootpassword
    reportsUsername: reports
    reportsPassword: reportspassword

frontend:
### В чарте frontend отсутствуют некоторые важные файлы. Поймите какие и опишите их.
  replicas: 1
  revisionHistoryLimit: 15
  strategy:
    type: Recreate
  service:
    port: 80
  ingress:
    host: nagaitsev.2sem.students-projects.ru # Корректный домен будет указан в задании
    path: /
    pathType: Prefix
  containerPort: 80
  image: norff/sausage-frontend:latest
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "128Mi"
      cpu: "1"
  nginxConf: nginx.conf

backend:
  annotations:
    path: /actuator/prometheus
    port: "8080"
    scrape: "true"
  env:
    postgresUri: jdbc:postgresql://postgresql:5432/sausage-store
    postgresUser: store
    postgresPassword: storepassword
    reportPath: /logs/reports
    logPath: /logs
  service:
    port: 8080
  revisionHistoryLimit: 15
  replicas: 1
  image: norff/sausage-backend:latest
  imagePullPolicy: Always
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "1"
  containerPort: 8080
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  livenessProbe:
    httpGet:
      path: /actuator/health
      port: 8080
    initialDelaySeconds: 30
    periodSeconds: 60
    failureThreshold: 3
    timeoutSeconds: 5
  vpa:
    enabled: true
    minAllowed:
      memory: "200Mi"
      cpu: "100m"
    maxAllowed:
      memory: "700Mi"
      cpu: "1"


backend-report:
  image_tag: latest
  revisionHistoryLimit: 15
  replicas: 1
  containerPort: 8080
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "250m"
  strategy:
    type: Recreate
  service:
    port: 8080
  config:
    port: 8080
  secret:
    dbport: 27017
    dbhost: mongodb
    dbname: sausage-store
    dbuser: reports
    dbpassword: reportspassword
  livenessProbe:
    httpGet:
      path: /api/v1/health
      port: 8080
    initialDelaySeconds: 15
    periodSeconds: 10
  hpa:
    minReplicas: 1
    maxReplicas: 5
    averageUtilization: 75

### Опишите значения для backend-report
### Приложение должно использовать стратегию Recreate
### Приложение использует переменную PORT - порт, на котором оно запустится и DB - Uri-подключение к mongodb. 
### DB положите в Secret, PORT в ConfigMap
### Опишите HPA для backend-report

infra:
  postgresql:
    enabled: true
    image: postgres:14
    port: 5432
    database: sausage-store
    username: store
    password: storepassword
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "200m"
        memory: "256Mi"
    persistence:
      enabled: true
      storageClass: ""
      size: 2Gi
    

  ### Опишите необходимые переменные для развертывания PostgresQL в кластере Kubernetes
    mongodb:
    image: mongo:7.0
    env:
      MONGO_INITDB_DATABASE: sausage-store
    auth:
      rootUsername: "{{ .Values.secrets.mongodb.rootUsername }}"
      rootPassword: "{{ .Values.secrets.mongodb.rootPassword }}"
      reportsUsername: "{{ .Values.secrets.mongodb.reportsUsername }}"
      reportsPassword: "{{ .Values.secrets.mongodb.reportsPassword }}"
    containerPort: 27017
    resources:
      requests:
        memory: "128Mi"
        cpu: "50m"
      limits:
        memory: "256Mi"
        cpu: "500m"
    storage:
      size: 1Gi
      storageClassName: local-path
