apiVersion: batch/v1
kind: Job
metadata:
  name: mongodb-init
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: mongodb-init
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/version: "{{ .Chart.AppVersion }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app.kubernetes.io/component: infra
    app.kubernetes.io/part-of: sausage-store
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "10"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mongodb-init
        app.kubernetes.io/instance: "{{ .Release.Name }}"
    spec:
      containers:
        - name: mongodb-init
          image: mongo:7.0
          command:
            - sh
            - -c
            - |
              until mongosh --host mongodb --port 27017 \
                -u {{ .Values.mongodb.env.MONGO_INITDB_ROOT_USERNAME }} \
                -p {{ .Values.mongodb.env.MONGO_INITDB_ROOT_PASSWORD }} \
                --authenticationDatabase admin \
                --eval 'db.adminCommand("ping")'; do
                echo "Waiting for MongoDB to be ready...";
                sleep 5;
              done;

              mongosh --host mongodb --port 27017 \
                -u {{ .Values.mongodb.env.MONGO_INITDB_ROOT_USERNAME }} \
                -p {{ .Values.mongodb.env.MONGO_INITDB_ROOT_PASSWORD }} \
                --authenticationDatabase admin \
                --eval '
                db = db.getSiblingDB("reports");
                if (!db.getUser("reports_user")) {
                  db.createUser({
                    user: "reports_user",
                    pwd: "reports_password",
                    roles: [
                      { role: "readWrite", db: "reports" }
                    ]
                  });
                } else {
                  print("User reports_user already exists.");
                }'
      restartPolicy: OnFailure