apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-mongodb-init
  namespace: {{ .Release.Namespace }}
  labels: 
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/version: "{{ .Chart.AppVersion }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app.kubernetes.io/component: infra
    app.kubernetes.io/part-of: sausage-store
spec:
  template:
    metadata:
      name: {{ .Release.Name }}-mongodb-init
      namespace: {{ .Release.Namespace }}
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mongodb-init
        app.kubernetes.io/instance: "{{ .Release.Name }}"
    spec:
      containers:
        - name: mongodb-init
          image: mongo:7.0
          resources:
            requests:
              memory: "128Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "100m"
          command:
            - sh
            - -c
            - |
              until mongosh --host mongodb --port 27017 \
                -u {{ .Values.mongodb.env.MONGO_INITDB_ROOT_USERNAME }} \
                -p {{ .Values.mongodb.env.MONGO_INITDB_ROOT_PASSWORD }} \
                --authenticationDatabase admin \
                --eval 'db.adminCommand("ping")'; do
                echo "Waiting for MongoDB to be ready...";
                sleep 5;
              done;

              mongosh --host mongodb --port 27017 \
                -u {{ .Values.mongodb.env.MONGO_INITDB_ROOT_USERNAME }} \
                -p {{ .Values.mongodb.env.MONGO_INITDB_ROOT_PASSWORD }} \
                --authenticationDatabase admin \
                --eval '
                db = db.getSiblingDB("sausage-store");
                if (!db.getUser("store")) {
                  db.createUser({
                    user: "store",
                    pwd: "storepassword",
                    roles: [
                      { role: "readWrite", db: "sausage-store" }
                    ]
                  });
                } else {
                  print("User store already exists.");
                }'
      restartPolicy: OnFailure
