-- Создание таблиц
CREATE TABLE public.product (
    id int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "name" varchar(255) NOT NULL,
    picture_url varchar(255) NULL
);

CREATE TABLE public.product_info (
    product_id int8 NOT NULL,
    "name" varchar(255) NOT NULL,
    price float8 NULL
);

CREATE TABLE public.orders (
    id int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    status varchar(255) NULL
);

CREATE TABLE public.orders_date (
    order_id int8 NOT NULL,
    status varchar(255) NULL,
    date_created date DEFAULT CURRENT_DATE NULL
);

CREATE TABLE public.order_product (
    quantity int4 NOT NULL,
    order_id int8 NOT NULL,
    product_id int8 NOT NULL
);