apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-report-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: backend-report
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: backend-report
    app.kubernetes.io/part-of: sausage-store
spec:
  replicas: {{ .Values.backendReport.replicas }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: backend-report
  template:
    metadata:
      labels:
        app: backend-report
    spec:
      containers:
        - name: backend-report
          image: "{{ .Values.backendReport.image }}:{{ .Values.backendReport.tag }}"
          imagePullPolicy: {{ .Values.backendReport.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.backendReport.containerPort }}
          envFrom:
            - configMapRef:
                name: backend-report-config
            - secretRef:
                name: backend-report-secrets
          resources:
            requests:
              memory: {{ .Values.backendReport.resources.requests.memory }}
              cpu: {{ .Values.backendReport.resources.requests.cpu }}
            limits:
              memory: {{ .Values.backendReport.resources.limits.memory }}
              cpu: {{ .Values.backendReport.resources.limits.cpu }}
              