{{- if .Values.backendReport.hpa.enabled }}
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: backend-report-hpa-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: backend-report
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend-report-{{ .Release.Name }}
  minReplicas: {{ .Values.backendReport.hpa.minReplicas }}
  maxReplicas: {{ .Values.backendReport.hpa.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.backendReport.hpa.targetCPUUtilizationPercentage }}
{{- end }}
