---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-secret
type: Opaque
stringData:
  DB: "mongodb://{{ .Values.secret.dbuser }}:{{ .Values.secret.dbpassword }}@mongodb:27017/sausage-store"
