apiVersion: v1
kind: Secret
metadata:
  name: backend-report-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: backend-report
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
data:
  DB_URI: {{ .Values.secret.DB_URI | b64enc | quote }}
  
